### ISSUE TITLE
theengs not startin in ubuntu 22.04.1 LTS

### ISSUE THREAD

**Issue by eerorossi** [theengs/gateway#51]
**Describe the bug**
Theengs does not start after upgrading ubuntu from 20.04 to 22.04.1 LTS. The setup and installation has not been changed in any way after the upgrade. theengs was working perfectly in 20.04.

**To Reproduce**
1. python3 -m TheengsGateway -H "192.168.1.179" -u "user" -p "password"
2. Expected data: theengs starts
3. See error: "Missing or invalid MQTT host parameters"

**Expected behavior**
Theengs shoud start the same way as in previous ubuntu version

**Screenshots**

**Environment (please complete the following information):**
* version used: 0.4.0
* Ubuntu 22.04.1

**Additional context**

* You should not have a compilation error if you use the versions of the libraries linked into the libraries folder, this badges show you the state of the compilation 
[![Build Status](https://github.com/theengs/decoder/workflows/Build/badge.svg?branch=development)](https://github.com/theengs/decoder/actions)
* If you are not sure this is a bug or an enhancement post your question to the forum

**Comment by eerorossi** [comment]
The reason was, that ubuntu upgrade lost bluetooth drivers. The issue was fixed by "sudo apt-get install bluez*"
